dev_logger:
  level: "DEBUG"
  format: "%(asctime)s - %(codename)s - %(name)s - %(levelname)s - %(message)s"
  file_handler: "local.log"
  remote_server_domain: "192.168.31.134"
  remote_server_port: 514